### PR TITLE
Expose middleware to allow inspection of the currently stacked middle…

### PR DESCRIPTION
**Pull request by lbdremy**
…wares

### CODE REVIEW

**Comment by jonathanong** [comment]
why do you need to inspect it?

**Comment by lbdremy** [comment]
For example, I want to access a middleware, which happens to have also have a prop, and I want to use this prop to generate documentation or something else from it.

```
const createMiddleware = (schema) => {
 const middleware = async (ctx, next) => {
   const valid = validator(schema, ctx.body);
  if (!valid) ctx.status = 400;
  return next();
 };
middleware.schema = schema;
};

// some other file

module.exports = compose([
 createMiddleware({ email: joi.email().required() },
async (ctx, next) {
 // check email does not exists
}
]);

// some other file

const middlewaresComposed = require('../somewhere');

middlewaresComposed.middleware[0].schema // do want ever you want

```

**Comment by jonathanong** [comment]
please rebase and linting. thanks!

**Comment by jonathanong** [comment]
also, a test!

**Pull request closed without merging**
