### PR TITLE
improve compose logic.

### PR DESCRIPTION
**Pull request by zensh**
**branch composer:**

``` sh
compose
114,158 op/s » (fn * 1)
64,464 op/s » (fn * 2)
33,850 op/s » (fn * 4)
16,501 op/s » (fn * 8)
8,891 op/s » (fn * 16)
4,502 op/s » (fn * 32)
2,214 op/s » (fn * 64)
1,079 op/s » (fn * 128)
574 op/s » (fn * 256)
273 op/s » (fn * 512)
136 op/s » (fn * 1024)
63 op/s » (fn * 2048)
27 op/s » (fn * 4096)
11 op/s » (fn * 8192)


Suites:  1
Benches: 14
Elapsed: 32,302.83 ms
```

**banch next-57-iterator:**

```
compose
85,536 op/s » (fn * 1)
45,344 op/s » (fn * 2)
21,636 op/s » (fn * 4)
9,103 op/s » (fn * 8)
4,284 op/s » (fn * 16)
2,626 op/s » (fn * 32)
1,392 op/s » (fn * 64)
671 op/s » (fn * 128)
339 op/s » (fn * 256)
164 op/s » (fn * 512)
77 op/s » (fn * 1024)
36 op/s » (fn * 2048)
14 op/s » (fn * 4096)
6 op/s » (fn * 8192)


Suites:  1
Benches: 14
Elapsed: 44,373.84 ms
```

### CODE REVIEW

**Comment by fundon** [comment]
Hi @zensh，Could you add below implementations?

* From https://github.com/koajs/compose/pull/57

```js
'use strict'

const Promise = require('any-promise')

/**
 * Make an iterator for middleware.
 */

const iterable = Object.create({
  [Symbol.iterator] (middleware, length, context, nextFunc) {
    return {
      next (i) {
        i |= 0
        const fn = middleware[i] || nextFunc
        let called = false

        return {
          done: i === length,
          value: fn && fn(context, () => {
            if (called) {
              throw new Error('next() called multiple times')
            }
            called = true
            return Promise.resolve().then(() => this.next(i + 1).value)
          })
        }
      }
    }
  }
})

/**
 * Expose compositor.
 */

module.exports = compose

/**
 * Compose `middleware` returning
 * a fully valid middleware comprised
 * of all those which are passed.
 *
 * @param {Array} middleware
 * @return {Function}
 * @api public
 */

function compose (middleware) {
  if (!Array.isArray(middleware)) throw new TypeError('Middleware stack must be an array!')
  for (const fn of middleware) {
    if (typeof fn !== 'function') throw new TypeError('Middleware must be composed of functions!')
  }

  /**
   * @param {Object} context
   * @return {Promise}
   * @api public
   */

  return function (context, next) {
    // iterator
    const iter = iterable[Symbol.iterator](middleware, middleware.length, context, next)

    try {
      return Promise.resolve(iter.next().value)
    } catch (err) {
      return Promise.reject(err)
    }
  }
}
```

* From [trek-middleware iterator](https://github.com/trekjs/middleware/blob/master/index.js)

```js
const SYMBOL_ITERATOR = Symbol.iterator

module.exports = class Middleware extends Array {

  [SYMBOL_ITERATOR] () {
    return this
  }

  next (i = 0, context, nextFunc) {
    const fn = this[i] || nextFunc
    let called = false

    return {
      done: i === this.length,
      value: fn && fn(context, () => {
        if (called) {
          throw new Error('next() called multiple times')
        }
        called = true
        // If you really want to use in excess of 5k middleware, ex:
        // return i > 5120 ? Promise.resolve().then(() => this.next(i, context, nextFunc).value) : Promise.resolve(this.next(i, context, nextFunc).value)
        return Promise.resolve(this.next(i + 1, context, nextFunc).value)
      })
    }
  }

  compose (context, nextFunc) {
    try {
      return Promise.resolve(this[SYMBOL_ITERATOR]().next(0, context, nextFunc).value)
    } catch (err) {
      return Promise.reject(err)
    }
  }

}
```


* From [trek-middleware no-iterator](https://github.com/trekjs/middleware/blob/no-iterator/index.js)

```js
module.exports = class Middleware extends Array {

  next (i = 0, context, nextFunc) {
    const fn = this[i] || nextFunc
    let called = false

    return fn && fn(context, () => {
      if (called) {
        throw new Error('next() called multiple times')
      }
      called = true
      // If you really want to use in excess of 5k middleware, ex:
      // return i > 5120 ? Promise.resolve().then(() => this.next(i, context, nextFunc)) : Promise.resolve(this.next(i, context, nextFunc))
      return Promise.resolve(this.next(i + 1, context, nextFunc))
    })
  }

  compose (context, nextFunc) {
    try {
      return Promise.resolve(this.next(0, context, nextFunc))
    } catch (err) {
      return Promise.reject(err)
    }
  }

}
```

**Comment by zensh** [comment]
@fundon The bench results is in similar level, but all of them will enter an infinite loop #60

**From #57:**
```
112,231 op/s » (fn * 1)
59,663 op/s » (fn * 2)
30,350 op/s » (fn * 4)
15,372 op/s » (fn * 8)
7,739 op/s » (fn * 16)
3,878 op/s » (fn * 32)
1,952 op/s » (fn * 64)
935 op/s » (fn * 128)
474 op/s » (fn * 256)
220 op/s » (fn * 512)
108 op/s » (fn * 1024)
55 op/s » (fn * 2048)
21 op/s » (fn * 4096)
9 op/s » (fn * 8192)

Suites:  1
Benches: 14
Elapsed: 36,310.68 ms
```

**From trek-middleware iterator:**
```
119,979 op/s » (fn * 1)
66,681 op/s » (fn * 2)
34,120 op/s » (fn * 4)
18,616 op/s » (fn * 8)
9,094 op/s » (fn * 16)
4,706 op/s » (fn * 32)
2,371 op/s » (fn * 64)
1,166 op/s » (fn * 128)
569 op/s » (fn * 256)
293 op/s » (fn * 512)
138 op/s » (fn * 1024)
65 op/s » (fn * 2048)
29 op/s » (fn * 4096)
12 op/s » (fn * 8192)

Suites:  1
Benches: 14
Elapsed: 31,818.24 ms
```

**From trek-middleware no-iterator:**
```
109,900 op/s » (fn * 1)
63,592 op/s » (fn * 2)
34,442 op/s » (fn * 4)
17,785 op/s » (fn * 8)
9,155 op/s » (fn * 16)
4,589 op/s » (fn * 32)
2,275 op/s » (fn * 64)
1,158 op/s » (fn * 128)
584 op/s » (fn * 256)
278 op/s » (fn * 512)
129 op/s » (fn * 1024)
62 op/s » (fn * 2048)
29 op/s » (fn * 4096)
12 op/s » (fn * 8192)

Suites:  1
Benches: 14
Elapsed: 33,002.47 ms
```

**Comment by zensh** [comment]
@fundon there is no way to get "biggest performance improvement".
[trek-middleware no-iterator](https://github.com/trekjs/middleware/blob/no-iterator/index.js) is beautiful but need fixing.

**Comment by fundon** [comment]
> @fundon there is no way to get "biggest performance improvement".

Yes, I made a mistake.



> trek-middleware no-iterator is beautiful but need fixing.

Thank you. I will fix that.

**Pull request closed without merging**
