### PR TITLE
conserve this

### PR DESCRIPTION
**Pull request by bertho-zero**

### CODE REVIEW

**Comment by bertho-zero** [comment]
@dead-horse Can you look at this ?

**Comment by yeliex** [comment]
@dead-horse   Would you take a look at this?

**Comment by yeliex** [comment]
@fengmk2 @popomore Would you anyone please take a look at this?

**Comment by fengmk2** [comment]
keep this for what feature? koa use `ctx` request context, no more `this`.

**Comment by bertho-zero** [comment]
koa-compose is not only used for koa, https://github.com/feathersjs/hooks needs to keep `this`.

**Comment by yeliex** [comment]
> koa-compose is not only used for koa, https://github.com/feathersjs/hooks needs to keep `this`.

In my opinion, `koa-compose` is designed for `koa`, so the problem from other packages is not the main reason to update.

The case to me, in `koajs` usage,  is I found that if I use a method from a class, the `this` does not point to the class context

For example, 
```typescript
// controller/user.ts 
export default class System extends Controller {
    constructor(app: Application) {
        this.app = app;
    }
    async getAppConfig(ctx: Context) {
        ctx.body = this.app.config; // => this = undefined because koa-router dependent on koa-componse
    }
}

// router/system.ts
router.get('/path', controller.system.getAppConfig)
```

*I create the instance of the class when app init, the purpose is to provide a more rapid way to get something like app, db reference and more  *

**Comment by yeliex** [comment]
In the koa@v1 we use `this` for context instance and after upgrade to v2, use `ctx ` instead. One of the purposes is not to break the `this` of javascript.
`koa-compose` always set `this` to `null` break what the vanilla javascript performance

**Comment by dead-horse** [comment]
-1 for this. People will use arrow function and make them confused.

**Comment by yeliex** [comment]
> -1 for this. People will use arrow function and make them confused.

@dead-horse Thaks for attention.

Binding `this` to `null` is more confusing (why `this` not performed as vanilla js expected), and arrow function cannot cover all the situations. 

Take the change would not change a lot, users cloud also ignore it. But in some special cases, this helps many

**Comment by yeliex** [comment]
`koa-compose` should just compose the middlewares, but not change the code context. it would be more friendly to users.

**Comment by bertho-zero** [comment]
The context is lost and the purpose of this PR is to keep it precisely.

With or without this PR this test does not work:
```js
it('should keep this - from class', () => {
  let instance

  class Controller {
    async middleware(ctx, next) {
      await next()
      expect(this).toEqual(instance) // undefined
    }
  }

  instance = new Controller()

  const ctx = {}
  const stack = []

  stack.push(instance.middleware) // works only with `.bind(instance)` and changes of this PR

  return compose(stack)(ctx)
})
```

**Comment by fl0w** [comment]
I agree with @dead-horse, -1 on this.

**Comment by jonathanong** [comment]
👍 i don't see why this module only needs to support koa

**Comment by bertho-zero** [comment]
> `koa-compose` should just compose the middlewares, but not change the code context. it would be more friendly to users.

:+1: The purpose of this PR is to **KEEP** this, not to define a new context.

**Comment by bertho-zero** [comment]
> -1 for this. People will use arrow function and make them confused.

https://runkit.com/embed/xoy000d15wjg

You can see here that this is not the case.
The behavior of the arrow functions remains unchanged.

**Comment by dead-horse** [comment]
> The behavior of the arrow functions remains unchanged.

what I mean is **the different behavior between arrow function and common function**.

**Comment by bertho-zero** [comment]
Ah, and this is not the behavior we expect from an arrow function?

**Comment by dead-horse** [comment]
So I'd like to tell people **don't use `this` in composed middlewares** rather than **you can use `this` in common function, but you can't use `this` in arrow function**.

**Comment by bertho-zero** [comment]
I prefer to tell people **do as you want but it is not recommended to use this**

**Comment by bertho-zero** [comment]
https://github.com/koajs/compose/blob/25568a36509fefc58914bc2a7600f787b16aa0df/index.js#L42

I still haven't understood the logic.

Rather than keeping the normal behavior of 'this' in javascript, it would be better if koa-compose overwrites it with null explicitly, why?

**Pull request closed without merging**
