### PR TITLE
Using Array#reduce instead of recursion

### PR DESCRIPTION
**Pull request by AMalininHere**
That solution allows to compose 5000(or more) middlewares.

### CODE REVIEW

**Comment by jonathanong** [comment]
can you describe the cost/benefits more? if we could not compose more than 5k middleware before, can you add a test (separate commit) that fails prior to this PR?

**Comment by jonathanong** [comment]
also, why would you ever need more than 5k middleware?

**Comment by tj** [comment]
haha MOAR MIDDLEWARE

**Comment by jonathanong** [comment]
@AMalininHere if u rebase, we can look into this more

**Comment by jonathanong** [comment]
also, can you post benchmarks?

**Comment by imcrazytwkr** [comment]
@jonathanong I'm pretty sure the original pull request creator isn't going to reply any time soon. I've forked the repo and applied his pull request (code available [here](https://github.com/imcrazytwkr/compose/tree/reduce)). Here are the benchmark results ran on Node v8.1.0 (4.5Ghz Core i7 4790K with 32gigs RAM):
- Using current implementation (recursive calls)
Recursive calls screenshot
- Using `reduceRight` (using `.reverse().reduce` performs even worse)
Reduce screenshot
The results are kinda controversial since recursive calls have better op/s count but total elapsed time was always lower when reduce was used.

**Pull request closed without merging**
