### PR TITLE
next: use iterators

### PR DESCRIPTION
**Pull request by jonathanong**
see #57

### CODE REVIEW

**Comment by jonathanong** [comment]
`next` w/ node v6:

```bash
          47,633 op/s » (fn * 1)
          27,416 op/s » (fn * 2)
          14,978 op/s » (fn * 4)
           7,697 op/s » (fn * 8)
           3,882 op/s » (fn * 16)
           1,956 op/s » (fn * 32)
             999 op/s » (fn * 64)
             501 op/s » (fn * 128)
             244 op/s » (fn * 256)
             124 op/s » (fn * 512)
              61 op/s » (fn * 1024)
```

`next-57-iterator` w/ node v6:

```bash
          40,208 op/s » (fn * 1)
          19,946 op/s » (fn * 2)
           9,790 op/s » (fn * 4)
           5,038 op/s » (fn * 8)
           2,531 op/s » (fn * 16)
           1,275 op/s » (fn * 32)
             633 op/s » (fn * 64)
             315 op/s » (fn * 128)
             161 op/s » (fn * 256)
              78 op/s » (fn * 512)
              39 op/s » (fn * 1024)
                 wait » (fn * 2048)
```

@fundon i believe your iteration branch is faster because it is incorrect. see commits: https://github.com/koajs/compose/pull/59/commits/61ca920244a9716eac8ff2bc0714388a4dd035b2 and https://github.com/koajs/compose/pull/59/commits/04318f91ba3716a49e4d14cf85d3191c0ed4bcc4

**Comment by jonathanong** [comment]
those commits were merged to `next`, so they are now:

- 17b766ec803f07cb005237702a144e0bf8f2355f
- 755ab29bab4749787614d7546178fd949ee6416c

**Comment by jonathanong** [comment]
NOTE: tests are failing because my code doesn't support node < v6. not sure we should bother supporting versions lower than 6 when we officially release koa v2. maybe only support versions with native async/await.

**Comment by fundon** [comment]
The little thing.
```
(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
/home/travis/build/koajs/compose/index.js:33
      const { length } = middleware
            ^
SyntaxError: Unexpected token {
```

**Comment by jonathanong** [comment]
That's node v6 sorry.

**Comment by jonathanong** [comment]
Upgrade node

**Pull request closed without merging**
