### PR TITLE
Add browser support

### PR DESCRIPTION
**Pull request by Cap32**

### CODE REVIEW

**Comment by coderhaoxin** [comment]
commit 73a3838345df1bc48a3aea04007843e51a04fb6e `3.1.0` is missing! (on branch next). ❓ ❓

**Comment by tj** [comment]
hmm seems unnecessary, I can't imagine anyone running Koa in the browser :D

**Comment by jonathanong** [comment]
haha whoops. fixed. 

yeah i'm not sure why browser support is necessary

**Comment by Cap32** [comment]
Thanks for replying.

I'm not going to run Koa in browser, haha. I like Koa because of the middleware concept. I think this concept is suitable for browsers.

👀

**Comment by fl0w** [comment]
@Cap32 In such case, I'll argue this would suit better as a separate package.

**Comment by coderhaoxin** [comment]
> In such case, I'll argue this would suit better as a separate package.

+1

**Comment by Cap32** [comment]
> In such case, I'll argue this would suit better as a separate package.

Why? `koa-compose` is what I want. The only problem at this moment is most of browsers do not support ES6.

So did you mean I should copy and paste the source code of `koa-compose` to my project and then compile via `Babel`? 😂

**Comment by PlasmaPower** [comment]
@Cap32 The browser is a small use case unfortunately. It shouldn't be too much trouble to babel it yourself though.

**Comment by fl0w** [comment]
@Cap32 you don't have to copy the code. You can create a separate package, as `koa-compose-browser` with a `koa-compose` dependency.

**Comment by Cap32** [comment]
@fl0w Thanks.

**Pull request closed without merging**
