### PR TITLE
feature: flatten passed array before compose

### PR DESCRIPTION
**Pull request by fl0w**
This is step one to simplify koajs/koa#Application.use.
This is related to https://github.com/koajs/koa/pull/1153

### CODE REVIEW

**Comment by fl0w** [comment]
@fengmk2 would you mind taking a look at this one? Should be semver-minor.
We could bump compose then in Koa and close referenced PR in koa repo.

**Comment by 3imed-jaberi** [comment]
@jonathanong @niftylettuce @dead-horse @miwnwski I think it's time to merge this !

**Comment by niftylettuce** [comment]
v4.2.0 released of koa-compose @ https://github.com/koajs/compose/releases/tag/v4.2.0

**Comment by atian25** [comment]
What's the point of this feature?

it's a breaking change.

**Comment by mansonchor** [comment]
> @fengmk2 would you mind taking a look at this one? Should be semver-minor.
> We could bump compose then in Koa and close referenced PR in koa repo.

should be major version

**Comment by pecliu** [comment]
it's a breaking change.
should be major version.

**Comment by miwnwski** [comment]
Sorry, I fail to see how this is a breaking change? Mind explaining or showing by example?

**Comment by opl-** [comment]
The following code no longer works after this change because the array used when compose is called is no longer the same as the one in the user's code.
```js
const middleware = [];

app.use(compose(middleware));

middleware.push(async (ctx, next) => {/* ... */});
```

**Comment by niftylettuce** [comment]
If you are writing code like that, it's extremely bad practice to begin with.

**Comment by opl-** [comment]
I'll admit that depending on an implementation detail is a bad practice. I did it because I verified the implementation and decided that it's unlikely to change and is therefore "good enough for now". Being able to add new middleware after the route has been declared, on the other hand, is in my opinion a useful property as it allows the code to be more pluggable. My project documents this and tries to make the API safe against potential misuse. I'll likely just reimplement it myself to ensure my code doesn't break, especially if `koa-compose` makes the behavior in this PR the default. It is my fault after all.

That said, this doesn't change the fact that this is a breaking change. This is true especially when considering that this package is small enough that it's easy to exactly understand it's behavior and use that knowledge to set certain expectations.

I'm glad that the minor bump has already been pulled from npm. Thank you for maintaining this package and handling this issue in a timely manner.

**Comment by 3imed-jaberi** [comment]
I believe isn't a breaking change.

**Comment by miwnwski** [comment]
@opl- I see your point, and you're right.

As I remember it this behaviour has been explicitly denounced. However, I can't seem to find the original issue so either I misremember or my search-fu is broken today. This is also why I originally never considered this a breaking change, it's a big "no no" in my shop (by the way, [@fl0w is my previous "lost" account](https://github.com/koajs/discussions/issues/47) incase anyone wonders).

I'm on the fence here. I really dislike breaking peoples code but at the same time I'm not sure unsupported use should be encouraged, it's close to relying on internal implementation for a monkey patch. Javascript is a quirky language, its strengths comes from its dynamic nature (IMO) but guarding against all use- and misuse is impractical.

That being said, I feel like this is one of those "bug becomes a feature"-issues. This not a critical PR, it was created two years ago and nobody cared (I never merge my own PRs in Koa-repo), which leads me to agree with those in favour of this being a breaking change.

If it were me I'd release this as a new major as this is a nice-to-have-feature, at best. @niftylettuce and @dead-horse might disagree, and to be frank it's their call, at this point I'm a glorified issue maintainer :)

**Comment by niftylettuce** [comment]
@dead-horse Just wanted your OK before I did a major semver release to v5.0.0 with this.  I see you reverted it to keep the commit log in sync with what's latest in npm, but didn't want to step on toes.

**Comment by niftylettuce** [comment]
I definitely think the major semver bump is the right approach.  We shouldn't prevent features due to people's bad patterns.  We should instead do this semver major bump and add a deprecation notice for prior versions that if they upgrade, they will have to be aware of this issue and rewrite their code in advance.

**Comment by dead-horse** [comment]
I think it goes back to why we have this PR. The reason is that we want to support `app.use([mw1, mw2])` on koa, but as it stands now, there's no way to fix this at the koa-compose level. So I don't recommend to add this feature to koa-compose. If we still need to get koa to support `app.use([mw1, mw2])`, then let's just go to koa and create a PR for this feature.

**Comment by pecliu** [comment]
But `tag/v4.2.0` is still `app.use([mw1, mw2])` version now …

**Comment by atian25** [comment]
> But `tag/v4.2.0` is still `app.use([mw1, mw2])` version now …

it's DEPRECATED.

```bash
$ npm info koa-compose@4.2.0

koa-compose@4.2.0 | MIT | deps: none | versions: 16
compose Koa middleware
https://github.com/koajs/compose#readme

DEPRECATED ⚠️  - koa-compose@4.2.0 is a breaking version, please either use <= v4.1 or upgrade to v5.x once it is released
```

**Pull request merged**
